### ISSUE TITLE
"lua: ./otouto/bot.lua:18: You didn't set your bot token in config.lua!" Well I did.

### ISSUE THREAD

**Issue by NinjaTurtle007** [topkecleon/otouto#106]
I installed the bot as per the quick start instructions on an ubuntu.

Set the bot token and my user ID in the config file and launched it but it shows this:

>  ./launch.sh 
lua: ./otouto/bot.lua:18: You didn't set your bot token in config.lua!
stack traceback:
	[C]: in function 'assert'
	./otouto/bot.lua:18: in function 'init'
	./otouto/bot.lua:124: in function <./otouto/bot.lua:123>
	(...tail calls...)
	[C]: in ?
otouto has stopped. ^C to exit.
lua: ./otouto/bot.lua:18: You didn't set your bot token in config.lua!
stack traceback:
	[C]: in function 'assert'
	./otouto/bot.lua:18: in function 'init'
	./otouto/bot.lua:124: in function <./otouto/bot.lua:123>
	(...tail calls...)
	[C]: in ?
otouto has stopped. ^C to exit.
lua: ./otouto/bot.lua:18: You didn't set your bot token in config.lua!
stack traceback:
	[C]: in function 'assert'
	./otouto/bot.lua:18: in function 'init'
	./otouto/bot.lua:124: in function <./otouto/bot.lua:123>
	(...tail calls...)
	[C]: in ?
otouto has stopped. ^C to exit.

**Comment by topkecleon** [comment]
Looks like you didn't set your bot token in config.lua.

That assertion doesn't check for a valid token, just that config.bot_api_key is set to something.

**Comment by NinjaTurtle007** [comment]
well I 100% did set the token

**Comment by bb010g** [comment]
Could you post your config, with the token characters replaced by `X` or something?

**Comment by d0v1k** [comment]
Hi,
Did you mange to fix this?

**Comment by bb010g** [comment]
@d0v1k Same thing—could you post your config, with the token characters replaced by `X` or something?
