### ISSUE TITLE
Example Markdown Used in Plugins

### ISSUE THREAD

**Issue by rizaumami** [topkecleon/otouto#19]
Otouto [have support for markdwon](https://github.com/topkecleon/otouto/commit/80f363de440cd9352435f2eb47668a03be3abebe), but lacking for example plugins.  

Maybe you could modify `reddit.lua` to use markdown so the result (arguably) prettier.
So, instead of this:
[[redd.it/3bbhtt](https://redd.it/3bbhtt)] Text-to-Speech bot
[[redd.it/3bsec7](https://redd.it/3bsec7)] Unofficial collection of api wrappers
[[redd.it/3b0glc](https://redd.it/3b0glc)] Master List of Telegram Bots [Will be Updated]
[[redd.it/3c4bgw](https://redd.it/3c4bgw)] @epornerbot AKA The Porn Queen [NSFW]

We get this:
[Text-to-Speech bot](https://redd.it/3bbhtt)
[Unofficial collection of api wrappers](https://redd.it/3bsec7)
[Master List of Telegram Bots [Will be Updated]](https://redd.it/3b0glc)
[@epornerbot AKA The Porn Queen [NSFW]](https://redd.it/3c4bgw)

**Comment by TiagoDanin** [comment]
I liked the idea.

**Comment by topkecleon** [comment]
Many plugins have been updated to output using markdown, following a common style:
gSearch.lua
wikipedia.lua
reddit.lua
hackernews.lua
urbandictionary.lua
imdb.lua
etc
