### ISSUE TITLE
cannot open loc.en: No such file or directory

### ISSUE THREAD

**Issue by hejiann** [topkecleon/otouto#2]
$ lua bot.lua 

Loading configuration...
lua: cannot open loc.en: No such file or directory
stack traceback:
	[C]: in function 'dofile'
	config.lua:6: in main chunk
	[C]: in function 'dofile'
	bot.lua:34: in function 'bot_init'
	bot.lua:100: in main chunk
	[C]: in ?

**Comment by topkecleon** [comment]
Am aware. Solution is to change "loc.en" to "loc/en.lua". Will fix tonight.

--- Original Message ---

**Comment by topkecleon** [comment]
Fixed in latest push.
Issue closed.
