### ISSUE TITLE
Most of the times, google queries that contain CJK characters are ignored by otouto

### ISSUE THREAD

**Issue by dogtopus** [topkecleon/otouto#34]
Details:
* <strike>Queries that contain any length of the same CJK character (e.g. `/g 哈哈`, `/g 哈哈哈`, `/g 哈哈哈哈`, etc.) are recognized by otouto</strike>
* <strike>Some queries that contain different CJK characters and has length <= 2 also works, but some don't</strike>
* <strike>Different CJK characters with length > 2 are **not working**</strike>

EDIT: Forget these. It is way more complicated than I thought. Queries with certain character combinations work, most of them not, and I cannot figure out the pattern...

**Comment by topkecleon** [comment]
Interesting problem. I'll look into it.

**Comment by topkecleon** [comment]
otouto is receiving and processing these queries, and attempts to return a result. Fails. Will investigate further.

**Comment by topkecleon** [comment]
`[Error]: Bad Request: Message text must be in utf-8`

**Comment by topkecleon** [comment]
Title truncation was breaking character encoding.
Fixed in https://github.com/topkecleon/otouto/commit/f65e145bc3204b7eca5d74a07d62ed3bd3262896.
