### ISSUE TITLE
Implement methods and examples of sending media

### ISSUE THREAD

**Issue by luksireiku** [topkecleon/otouto#4]
You should implement methods and some example plugins to send various types of media like files, photos, audios, stickers...

**Comment by topkecleon** [comment]
Or you should. :)

**Comment by luksireiku** [comment]
I tried lots of times without success
:c

**Comment by JuanPotato** [comment]
Otouto v3 @topkecleon

**Comment by luksireiku** [comment]
YEAAAAAAAAAAH!

2015-11-15 21:21 GMT+01:00 Juan Potato <notifications@github.com>:

**Comment by JuanPotato** [comment]
@topkecleon isn't this fixed now?

**Comment by topkecleon** [comment]
Fixed with the most elegant piece of pure-Lua code ever. :^)
