### ISSUE TITLE
what is this????????????///

### ISSUE THREAD

**Issue by BH-YAGHI** [topkecleon/otouto#61]
Connection error                                                                                                                                           
Conflict: terminated by other long poll or webhook

**Comment by topkecleon** [comment]
Are you running two instances of the bot at the same time?

**Comment by BH-YAGHI** [comment]
No.if I close terminal and open new terminal so give this error !

**Comment by bb010g** [comment]
Please provide reliable steps to reproduce. I haven't ever got this on my end.

**Comment by topkecleon** [comment]
Closed for age and inactivity.
