### ISSUE TITLE
Improve help info

### ISSUE THREAD

**Issue by Adonai** [topkecleon/otouto#69]
Improvements proposal for `/help` screen

* Some useful commands are not printed
* It'd be nice to see what bot can do with mentions
* Some helpful non-slash commands like 's/text/replacement/' are completely missed

**Comment by topkecleon** [comment]
Can you elaborate on the second point?

**Comment by Adonai** [comment]
I mean, you can say "hey, otouto" and bot will answer. But I don't see it documented anywhere
