### ISSUE TITLE
Potentially spam patterns

### ISSUE THREAD

**Issue by rizaumami** [topkecleon/otouto#74]
```bash
s/./
/
```
Will replace every characters with newline, resulted in long empty post.

A simple check for newline could be added to https://github.com/topkecleon/otouto/blob/master/otouto/plugins/patterns.lua#L17, i.e:

```lua
if not m2 or m2:match('\n') then 
   return true 
end
```

**Comment by bb010g** [comment]
Spam like that seems to be more an admin's problem. There are legitimate uses for replacing characters with newline.

**Comment by topkecleon** [comment]
Whitespace is now trimmed from the beginning and end of a string after it has been processed. People spamming whitespace within a string is not something that should be fixed; refer to your group admin.
