### ISSUE TITLE
gImage nsfw search broken

### ISSUE THREAD

**Issue by soend** [topkecleon/otouto#80]
gImage NSFW image search is broken in the plugin atm. Instead of `utilities.send_reply('*NSFW*\n'..msg, output)` on line 60 it should be something like `utilities.send_reply(msg, '*NSFW*\n'..output)`

**Comment by topkecleon** [comment]
Fixed. Not sure how this came about.
Obviously I didn't notice it because I don't use the plugin anymore, and if it's been broken this long, probably no one else does, either.
