### ISSUE TITLE
Administration plugin doesn't work

### ISSUE THREAD

**Issue by unomas** [topkecleon/otouto#84]
Hello, in private and in supergroup, the basic commands work, such as:

> Available commands:
> • /8ball
> • /about
> • /calc <expression>
> • /cash [amount] <from> to <to>
> • /cat
> • /color [ffffff]
> • /commit
> • /echo <text>
> • /groups [query]
> • /hackernews
> • /help [command]
> • /imdb <query>
> • /location <query>
> • /me
> • /nick <nickname>
> • /ping
> • /pun
> • /reddit [r/subreddit | query]
> • /roll <nDr>
> • /shout <text>
> • /slap [target]
> • /time <location>
> • /urbandictionary <query>
> • /whoami
> • /wikipedia <query>
> • /xkcd [i]
> Arguments: <required> [optional]

- The `administration.lua` plugin is active
- I have tried adding a group to manage with `/gadd` in group, but it does not respond or does not return error.
- In `config.lua` the admin ID is included.
- `telegram-cli` installed and working, the bot has been restarted.
- If I execute the command `/ahelp` in group or private (with the account that has the admin ID), reply me in private with:

> Commands for Users:
> • /groups [query]
> • /ahelp [command]
> • /ops
> • /description
> • /rules [i]
> • /motd
> • /link
> Arguments: <required> [optional]

- With `/groups` say: There are currently no listed groups.
- With `/ops` : nothing happens
- With `/description` say: Group not found. Specify a group by name or ID, or use this command without arguments inside an administrated group.
- The remaining commands do not respond to any messages.

¿Any idea? Thanks

**Comment by topkecleon** [comment]
>I have tried adding a group to manage with /gadd in group, but it does not respond or an error appears.
What is the error?
Also, show me the contents of the plugins table in config.lua.

**Comment by unomas** [comment]
Sorry, I correct the above: There is no answer. No get error 
`config.lua` plugins:
```lua
 plugins = { -- To enable a plugin, add its name to the list.
        'users',
        'administration',
        'end_forwards',
        'blacklist',
        'about',
        'calc',
        'cats',
        'hexcolor',
        'commit',
        'control',
        'currency',
        'dice',
        'echo',
        'eightball',
        'location',
        'hackernews',
        'imdb',
        'me',
        'nick',
        'ping',
        'pun',
        'reddit',
        'shout',
        'slap',
        'time',
        'urbandictionary',
        'whoami',
        'wikipedia',
        'xkcd',
        -- Add new plugins here.
        'help',
        
    }
```

**Comment by topkecleon** [comment]
Does the group you're trying to add actually belong to you?
That's kind of important.

**Comment by unomas** [comment]
The group has been created by me, the same account that is admin in config.lua

**Comment by unomas** [comment]
If you want I can give you the information to access the server and the nick of the bot. Maybe you can see the problem more quickly, I do not know it can be going wrong

**Comment by topkecleon** [comment]
If it's failing without any notice, then an error will have been posted in your log_chat or to the console.
Please find this error and post it here.

**Comment by unomas** [comment]
I don't get any error in console or in log_chat.

I send `/groups`:
<img width="566" alt="send command groups" src="https://cloud.githubusercontent.com/assets/3227026/20260305/4932ac96-aa59-11e6-81f7-30cb8b28feee.png">

In console:
<img width="1065" alt="information of groups with command groups" src="https://cloud.githubusercontent.com/assets/3227026/20260322/62ed096a-aa59-11e6-97b2-b7cbf935a67b.png">

When i send `/gadd`:
<img width="534" alt="send command add group" src="https://cloud.githubusercontent.com/assets/3227026/20260342/7f01779e-aa59-11e6-8655-f919b061398d.png">

In console:
<img width="1062" alt="nothing with gadd" src="https://cloud.githubusercontent.com/assets/3227026/20260353/87fe24d2-aa59-11e6-841f-4c8dcc2c605a.png">

With `log_chat = '999999999', --@adminID` or `log_chat = nil,` I do not receive any errors in chat or console.

**Comment by unomas** [comment]
Solved, i'm very stupid XDDD
In config.lua i set:
```lua
-- Your Telegram ID.
    admin = '999999999',
```
This don't work and don't get error.

--------------------------------
```lua
-- Your Telegram ID.
    admin = 999999999,
```
This work.
